# Etapa de build
FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci
COPY . .
# Usa la variable del entorno de Vite si existe; por defecto ya pusimos /api/v1
RUN npm run build

# Etapa de runtime: Nginx
FROM nginx:alpine
# Proxy de /api a la API Flask
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
